version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: leaderboard_nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app
    working_dir: /app
    expose:
      - "8000"
    env_file:
      - backend/.env

  frontend:
    image: node:18.19.0
    restart: always
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install && npm run build && npm run preview -- --host"
    expose:
      - "4173"
    env_file:
      - app/.env
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"
