services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"   
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app
    working_dir: /app
    expose:
      - "8000"
    env_file:
      - backend/.env

  frontend:
    image: node:18.19.0
    restart: always
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"
    expose:
      - "5173"
    env_file:
      - app/.env
    depends_on:
      - backend
